### ISSUE TITLE
Should use priority string if converting to integer fails

### ISSUE THREAD

**Issue by spion** [jue89/node-systemd-journald#9]
https://github.com/jue89/node-systemd-journald/blob/12b17eed79bb9d385a75abb1128ced7d0e631d29/src/journal_send.cc#L50-L61

**Comment by jue89** [comment]
Hey!

Sorry for late responding.

Can you describe your problem a little bit more? I don't see what you expect the C++ bindings to do? Since the send function is called by the library itself and not the user, it should not be possible to call this function with something different than a number. Honestly, the check if the first argument is really a number is kind of redundant. But I'm not brave enough to remove it ;)

**Comment by spion** [comment]
Never mind - it seems like the problem is with winston-journald, not systemd-journald.
